import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import { FingerprintProvider } from "@/context/Fingerprint";
import QueryProvider from "@/context/QueryProvider";
import { Poppins } from "next/font/google";
import "./globals.css";
import { initWorker } from "@/redis";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  initWorker();
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased h-dvh flex flex-col overflow-hidden`}
      >
        <QueryProvider>
          <FingerprintProvider>
            <Header />
            {children}
          </FingerprintProvider>
          <Toaster richColors />
        </QueryProvider>
      </body>
    </html>
  );
}
